module.exports = [
  {
    authority_description: '文章管理',
    authority_id: 'AaZjGoX4K',
    authority_name: '文章管理',
    authority_parent_id: '',
    authority_parent_name: '',
    authority_sort: 1,
    authority_type: '1',
    authority_url: 'article_mange',
    enable: true
  },
  {
    authority_description: 'dasddasd',
    authority_id: 'M5_VrV7vx',
    authority_name: '文章汇总',
    authority_parent_id: 'AaZjGoX4K',
    authority_parent_name: '文章管理',
    authority_sort: 0,
    authority_type: '1',
    authority_url: 'article',
    enable: true
  },
  {
    authority_description: '查看文章列表的权限',
    authority_id: 'Jh8z1f7yt',
    authority_name: '获取文章列表',
    authority_parent_id: 'M5_VrV7vx',
    authority_parent_name: '文章汇总',
    authority_sort: 5,
    authority_type: '2',
    authority_url: '/article/list',
    enable: false
  },
  {
    authority_description: '修改文章的一些字段',
    authority_id: 'nGyHv8SMz',
    authority_name: '更新文章',
    authority_parent_id: 'M5_VrV7vx',
    authority_parent_name: '文章汇总',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/article/edit',
    enable: false
  },
  {
    authority_description: '删除文章的权限',
    authority_id: 'HtqdfZid0',
    authority_name: '删除文章',
    authority_parent_id: 'M5_VrV7vx',
    authority_parent_name: '文章汇总',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/article/delete',
    enable: false
  },
  {
    authority_description: '文章的标签栏修改',
    authority_id: 'QZuaQAqRs',
    authority_name: '文章标签',
    authority_parent_id: 'AaZjGoX4K',
    authority_parent_name: '文章管理',
    authority_sort: 1,
    authority_type: '1',
    authority_url: 'article_tag',
    enable: true
  },
  {
    authority_description: '获取文章所有的标签列表，并且分页',
    authority_id: 'fkXCvFOth',
    authority_name: '获取文章标签列表',
    authority_parent_id: 'QZuaQAqRs',
    authority_parent_name: '文章标签',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/article-tag/list',
    enable: false
  },
  {
    authority_description: '创建文章标签',
    authority_id: 'zJfUPY51P',
    authority_name: '创建文章标签',
    authority_parent_id: 'QZuaQAqRs',
    authority_parent_name: '文章标签',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/article-tag/create',
    enable: false
  },
  {
    authority_description: '更新文章标签',
    authority_id: 'r-tDtqr94',
    authority_name: '更新文章标签',
    authority_parent_id: 'QZuaQAqRs',
    authority_parent_name: '文章标签',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/article-tag/update',
    enable: false
  },
  {
    authority_description: '删除文章标签',
    authority_id: 'HkgJdDzEm',
    authority_name: '删除文章标签',
    authority_parent_id: 'QZuaQAqRs',
    authority_parent_name: '文章标签',
    authority_sort: 3,
    authority_type: '2',
    authority_url: '/article-tag/delete',
    enable: false
  },
  {
    authority_description: '文章专栏',
    authority_id: 'wFaa7X0k-',
    authority_name: '文章专栏',
    authority_parent_id: 'AaZjGoX4K',
    authority_parent_name: '文章管理',
    authority_sort: 2,
    authority_type: '1',
    authority_url: 'article_column',
    enable: true
  },
  {
    authority_description: '获取文章专栏列表',
    authority_id: 'vljPAaWsL',
    authority_name: '获取文章专栏列表',
    authority_parent_id: 'wFaa7X0k-',
    authority_parent_name: '文章专栏',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/article-column/list',
    enable: false
  },
  {
    authority_description: '创建文章专栏',
    authority_id: 'wamK-ehtL',
    authority_name: '创建文章专栏',
    authority_parent_id: 'wFaa7X0k-',
    authority_parent_name: '文章专栏',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/article-column/create',
    enable: false
  },
  {
    authority_description: '更新文章专栏',
    authority_id: 'C3WtKzxS_',
    authority_name: '更新文章专栏',
    authority_parent_id: 'wFaa7X0k-',
    authority_parent_name: '文章专栏',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/article-column/update',
    enable: false
  },
  {
    authority_description: '删除文章专栏',
    authority_id: 'klUA63clP',
    authority_name: '删除文章专栏',
    authority_parent_id: 'wFaa7X0k-',
    authority_parent_name: '文章专栏',
    authority_sort: 3,
    authority_type: '2',
    authority_url: '/article-column/delete',
    enable: false
  },
  {
    authority_description: '用户管理',
    authority_id: 'f-_KRK5ZL',
    authority_name: '用户管理',
    authority_parent_id: '',
    authority_parent_name: '',
    authority_sort: 1,
    authority_type: '1',
    authority_url: 'user_manger',
    enable: true
  },
  {
    authority_description: '用户管理',
    authority_id: 'lnRP0Lc5L',
    authority_name: '用户',
    authority_parent_id: 'f-_KRK5ZL',
    authority_parent_name: '用户管理',
    authority_sort: 0,
    authority_type: '1',
    authority_url: 'user',
    enable: true
  },
  {
    authority_description: '获取用户列表',
    authority_id: 'YaLP9BQoz',
    authority_name: '获取用户列表',
    authority_parent_id: 'lnRP0Lc5L',
    authority_parent_name: '用户',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/user/list',
    enable: false
  },
  {
    authority_description: '更新用户',
    authority_id: 'm9a-NQsky',
    authority_name: '更新用户',
    authority_parent_id: 'lnRP0Lc5L',
    authority_parent_name: '用户',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/user/edit',
    enable: false
  },
  {
    authority_description: '删除用户',
    authority_id: 'PUDwKVudl',
    authority_name: '删除用户',
    authority_parent_id: 'lnRP0Lc5L',
    authority_parent_name: '用户',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/user/delete',
    enable: false
  },
  {
    authority_description: '用户角色',
    authority_id: 'Fg5quebwd',
    authority_name: '用户角色',
    authority_parent_id: 'f-_KRK5ZL',
    authority_parent_name: '用户管理',
    authority_sort: 1,
    authority_type: '1',
    authority_url: 'user_role',
    enable: true
  },
  {
    authority_description: '获取用户角色列表',
    authority_id: 'orz0bQnAV',
    authority_name: '获取用户角色列表',
    authority_parent_id: 'Fg5quebwd',
    authority_parent_name: '用户角色',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/user-role/list',
    enable: false
  },
  {
    authority_description: '创建用户角色',
    authority_id: 'FWJS6cW_t',
    authority_name: '创建用户角色',
    authority_parent_id: 'Fg5quebwd',
    authority_parent_name: '用户角色',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/user-role/create',
    enable: false
  },
  {
    authority_description: '获取全部用户角色',
    authority_id: 'XFLI-Xiu9',
    authority_name: '获取全部用户角色',
    authority_parent_id: 'Fg5quebwd',
    authority_parent_name: '用户角色',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/user-role/all',
    enable: false
  },
  {
    authority_description: '更新用户角色',
    authority_id: 'rc8PyN-7e',
    authority_name: '更新用户角色',
    authority_parent_id: 'Fg5quebwd',
    authority_parent_name: '用户角色',
    authority_sort: 3,
    authority_type: '2',
    authority_url: '/user-role/update',
    enable: false
  },
  {
    authority_description: '删除用户角色',
    authority_id: 'FLcVmwUGf',
    authority_name: '删除用户角色',
    authority_parent_id: 'Fg5quebwd',
    authority_parent_name: '用户角色',
    authority_sort: 4,
    authority_type: '2',
    authority_url: '/user-role/delete',
    enable: false
  },
  {
    authority_description: '文章评论管理',
    authority_id: 'yoUnDy1tf',
    authority_name: '评论管理',
    authority_parent_id: 'f-_KRK5ZL',
    authority_parent_name: '用户管理',
    authority_sort: 2,
    authority_type: '1',
    authority_url: 'comment',
    enable: true
  },
  {
    authority_description: '获取评论列表',
    authority_id: 'vAlRwG42i',
    authority_name: '获取评论列表',
    authority_parent_id: 'yoUnDy1tf',
    authority_parent_name: '评论管理',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/article-comment/list',
    enable: false
  },
  {
    authority_description: '更新评论',
    authority_id: 'Aj46PocjE',
    authority_name: '更新评论',
    authority_parent_id: 'yoUnDy1tf',
    authority_parent_name: '评论管理',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/article-comment/update',
    enable: false
  },
  {
    authority_description: '删除评论',
    authority_id: 'NgMPyBTyt',
    authority_name: '删除评论',
    authority_parent_id: 'yoUnDy1tf',
    authority_parent_name: '评论管理',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/article-comment/delete',
    enable: false
  },
  {
    authority_description: '网站管理',
    authority_id: '62EbYFQ4K',
    authority_name: '网站管理',
    authority_parent_id: '',
    authority_parent_name: '',
    authority_sort: 2,
    authority_type: '1',
    authority_url: 'web',
    enable: true
  },
  {
    authority_description: '图库',
    authority_id: 'Fg332SacC',
    authority_name: '图库',
    authority_parent_id: '62EbYFQ4K',
    authority_parent_name: '网站管理',
    authority_sort: 1,
    authority_type: '1',
    authority_url: 'picture',
    enable: true
  },
  {
    authority_description: '获取图片列表',
    authority_id: 'hKNBbz3Id',
    authority_name: '获取图片列表',
    authority_parent_id: 'Fg332SacC',
    authority_parent_name: '图库',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/picture/list',
    enable: false
  },
  {
    authority_description: '上传图片',
    authority_id: '7H5NYaABj',
    authority_name: '上传图片',
    authority_parent_id: 'Fg332SacC',
    authority_parent_name: '图库',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/picture/create',
    enable: false
  },
  {
    authority_description: '更新图片',
    authority_id: '2tQfFmmDr',
    authority_name: '更新图片',
    authority_parent_id: 'Fg332SacC',
    authority_parent_name: '图库',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/picture/update',
    enable: false
  },
  {
    authority_description: '删除图片',
    authority_id: 'huW07hjGn',
    authority_name: '删除图片',
    authority_parent_id: 'Fg332SacC',
    authority_parent_name: '图库',
    authority_sort: 3,
    authority_type: '2',
    authority_url: '/picture/delete',
    enable: false
  },
  {
    authority_description: '系统管理',
    authority_id: 'mmnVfpVml',
    authority_name: '系统管理',
    authority_parent_id: '',
    authority_parent_name: '',
    authority_sort: 3,
    authority_type: '1',
    authority_url: 'admin',
    enable: true
  },
  {
    authority_description: '管理员管理',
    authority_id: 'jKF3lIYO0',
    authority_name: '管理员管理',
    authority_parent_id: 'mmnVfpVml',
    authority_parent_name: '系统管理',
    authority_sort: 0,
    authority_type: '1',
    authority_url: 'admin_user',
    enable: true
  },
  {
    authority_description: '获取管理员列表',
    authority_id: '51F3xJ4YB',
    authority_name: '获取管理员列表',
    authority_parent_id: 'jKF3lIYO0',
    authority_parent_name: '管理员管理',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/admin-user/list',
    enable: false
  },
  {
    authority_description: '创建管理员',
    authority_id: 'WCfpKOn6q',
    authority_name: '创建管理员',
    authority_parent_id: 'jKF3lIYO0',
    authority_parent_name: '管理员管理',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/admin-user/create',
    enable: false
  },
  {
    authority_description: '更新管理员',
    authority_id: '37xmomJUP',
    authority_name: '更新管理员',
    authority_parent_id: 'jKF3lIYO0',
    authority_parent_name: '管理员管理',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/admin-user/edit',
    enable: false
  },
  {
    authority_description: '删除管理员',
    authority_id: 'rK9yps5-n',
    authority_name: '删除管理员',
    authority_parent_id: 'jKF3lIYO0',
    authority_parent_name: '管理员管理',
    authority_sort: 3,
    authority_type: '2',
    authority_url: '/admin-user/delete',
    enable: false
  },
  {
    authority_description: '角色管理',
    authority_id: 'f__A7Zf22',
    authority_name: '角色管理',
    authority_parent_id: 'mmnVfpVml',
    authority_parent_name: '系统管理',
    authority_sort: 1,
    authority_type: '1',
    authority_url: 'admin_role',
    enable: true
  },
  {
    authority_description: '获取角色列表',
    authority_id: 'IIjFU1b32',
    authority_name: '获取角色列表',
    authority_parent_id: 'f__A7Zf22',
    authority_parent_name: '角色管理',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/admin-role/list',
    enable: false
  },
  {
    authority_description: '创建角色',
    authority_id: 'e1AenAQGh',
    authority_name: '创建角色',
    authority_parent_id: 'f__A7Zf22',
    authority_parent_name: '角色管理',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/admin-role/create',
    enable: false
  },
  {
    authority_description: '更新角色',
    authority_id: 'KE5weIvJm',
    authority_name: '更新角色',
    authority_parent_id: 'f__A7Zf22',
    authority_parent_name: '角色管理',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/admin-role/edit',
    enable: false
  },
  {
    authority_description: '删除角色',
    authority_id: 'nImMMukuO',
    authority_name: '删除角色',
    authority_parent_id: 'f__A7Zf22',
    authority_parent_name: '角色管理',
    authority_sort: 3,
    authority_type: '2',
    authority_url: '/admin-role/delete',
    enable: false
  },
  {
    authority_description: '权限菜单',
    authority_id: 'kl66VGwzs',
    authority_name: '权限菜单',
    authority_parent_id: 'mmnVfpVml',
    authority_parent_name: '系统管理',
    authority_sort: 2,
    authority_type: '1',
    authority_url: 'admin_authority',
    enable: true
  },
  {
    authority_description: '获取所有权限菜单',
    authority_id: 'm60NSV9Uf',
    authority_name: '获取所有权限菜单',
    authority_parent_id: 'kl66VGwzs',
    authority_parent_name: '权限菜单',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/admin-authority/list',
    enable: false
  },
  {
    authority_description: '创建权限',
    authority_id: 'uNcakD-iu',
    authority_name: '创建权限',
    authority_parent_id: 'kl66VGwzs',
    authority_parent_name: '权限菜单',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/admin-authority/create',
    enable: false
  },
  {
    authority_description: '更新权限',
    authority_id: 'PrlXMUprO',
    authority_name: '更新权限',
    authority_parent_id: 'kl66VGwzs',
    authority_parent_name: '权限菜单',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/admin-authority/update',
    enable: false
  },
  {
    authority_description: '删除权限',
    authority_id: 'DD7uvMFqf',
    authority_name: '删除权限',
    authority_parent_id: 'kl66VGwzs',
    authority_parent_name: '权限菜单',
    authority_sort: 3,
    authority_type: '2',
    authority_url: '/admin-authority/delete',
    enable: false
  },
  {
    authority_description: '系统配置',
    authority_id: 'EdU0eCL53',
    authority_name: '系统配置',
    authority_parent_id: 'mmnVfpVml',
    authority_parent_name: '系统管理',
    authority_sort: 3,
    authority_type: '1',
    authority_url: 'system_config',
    enable: false
  },
  {
    authority_description: '查看系统配置',
    authority_id: 'tpm47b-0g',
    authority_name: '查看系统配置',
    authority_parent_id: 'EdU0eCL53',
    authority_parent_name: '系统配置',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/system-config/info',
    enable: false
  },
  {
    authority_description: '更新系统配置',
    authority_id: 'U2Q9FyWqT',
    authority_name: '更新系统配置',
    authority_parent_id: 'EdU0eCL53',
    authority_parent_name: '系统配置',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/system-config/update',
    enable: false
  },
  {
    authority_description: '系统日志',
    authority_id: 'F1-0EJhfj',
    authority_name: '系统日志',
    authority_parent_id: 'mmnVfpVml',
    authority_parent_name: '系统管理',
    authority_sort: 4,
    authority_type: '1',
    authority_url: 'admin_system_log',
    enable: true
  },
  {
    authority_description: '获取系统日志列表',
    authority_id: 'LV2W44Iea',
    authority_name: '获取系统日志列表',
    authority_parent_id: 'F1-0EJhfj',
    authority_parent_name: '系统日志',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/admin-system-log/list',
    enable: false
  },
  {
    authority_description: '删除系统日志',
    authority_id: 'SpJ9AeDIP',
    authority_name: '删除系统日志',
    authority_parent_id: 'F1-0EJhfj',
    authority_parent_name: '系统日志',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/admin-system-log/delete',
    enable: false
  },
  {
    authority_description: '一次获取所有的文章标签',
    authority_id: 'sL8GD5TNz',
    authority_name: '获取全部文章标签',
    authority_parent_id: 'QZuaQAqRs',
    authority_parent_name: '文章标签',
    authority_sort: 4,
    authority_type: '2',
    authority_url: '/article-tag/all',
    enable: false
  },
  {
    authority_description: '一次性获取全部的管理员用户角色',
    authority_id: 'yG6HFsIaE',
    authority_name: '获取全部角色',
    authority_parent_id: 'f__A7Zf22',
    authority_parent_name: '角色管理',
    authority_sort: 4,
    authority_type: '2',
    authority_url: '/admin-role/all',
    enable: false
  },
  {
    authority_description: '网站配置公告等等',
    authority_id: 'BvTHaZGiy',
    authority_name: '网站配置',
    authority_parent_id: '62EbYFQ4K',
    authority_parent_name: '网站管理',
    authority_sort: 1,
    authority_type: '1',
    authority_url: 'website_config',
    enable: true
  },
  {
    authority_description: '创建网站配置',
    authority_id: 'JFqDhmDlD',
    authority_name: '创建网站配置',
    authority_parent_id: 'BvTHaZGiy',
    authority_parent_name: '网站配置',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/options/create',
    enable: false
  },
  {
    authority_description: '更新网站配置',
    authority_id: 'glXE-ZYMj',
    authority_name: '更新网站配置',
    authority_parent_id: 'BvTHaZGiy',
    authority_parent_name: '网站配置',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/options/update',
    enable: false
  },
  {
    authority_description: '删除网站配置',
    authority_id: 'zrjH_hLgq',
    authority_name: '删除网站配置',
    authority_parent_id: 'BvTHaZGiy',
    authority_parent_name: '网站配置',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/options/delete',
    enable: false
  },
  {
    authority_description: '获取网站配置项列表',
    authority_id: 'n47GLlyLh',
    authority_name: '获取网站配置项列表',
    authority_parent_id: 'BvTHaZGiy',
    authority_parent_name: '网站配置',
    authority_sort: 3,
    authority_type: '2',
    authority_url: '/options/list',
    enable: false
  },
  {
    authority_description: '用户权限',
    authority_id: '8nzhEmgmS',
    authority_name: '用户权限',
    authority_parent_id: 'f-_KRK5ZL',
    authority_parent_name: '用户管理',
    authority_sort: 3,
    authority_type: '1',
    authority_url: 'user_authority',
    enable: true
  },
  {
    authority_description: '获取用户权限列表',
    authority_id: 'hDzP4R-nh',
    authority_name: '获取用户权限列表',
    authority_parent_id: '8nzhEmgmS',
    authority_parent_name: '用户权限',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/user-authority/list',
    enable: false
  },
  {
    authority_description: '创建用户权限',
    authority_id: '8narmMp7Z',
    authority_name: '创建用户权限',
    authority_parent_id: '8nzhEmgmS',
    authority_parent_name: '用户权限',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/user-authority/create',
    enable: false
  },
  {
    authority_description: '更新用户权限',
    authority_id: 'diWnCwOeO',
    authority_name: '更新用户权限',
    authority_parent_id: '8nzhEmgmS',
    authority_parent_name: '用户权限',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/user-authority/update',
    enable: false
  },
  {
    authority_description: '删除用户权限',
    authority_id: 'xlhPC3Ca3',
    authority_name: '删除用户权限',
    authority_parent_id: '8nzhEmgmS',
    authority_parent_name: '用户权限',
    authority_sort: 3,
    authority_type: '2',
    authority_url: '/user-authority/delete',
    enable: false
  },
  {
    authority_description: '设置用户角色权限',
    authority_id: '13ZrguVlC',
    authority_name: '设置用户角色权限',
    authority_parent_id: '8nzhEmgmS',
    authority_parent_name: '用户权限',
    authority_sort: 4,
    authority_type: '2',
    authority_url: '/user-role-authority/set',
    enable: false
  },
  {
    authority_description: '设置管理员角色',
    authority_id: 'bjrc297SQ',
    authority_name: '设置管理员角色',
    authority_parent_id: 'jKF3lIYO0',
    authority_parent_name: '管理员管理',
    authority_sort: 4,
    authority_type: '2',
    authority_url: '/admin-user-role/create',
    enable: false
  },
  {
    authority_description: '管理员角色设置权限',
    authority_id: 'e7yBRAOsE',
    authority_name: '管理员角色设置权限',
    authority_parent_id: 'f__A7Zf22',
    authority_parent_name: '角色管理',
    authority_sort: 5,
    authority_type: '2',
    authority_url: '/admin-role-authority/set',
    enable: false
  },
  {
    authority_description: '用户头像审核',
    authority_id: 'F2cVbkCIn',
    authority_name: '用户头像审核',
    authority_parent_id: 'f-_KRK5ZL',
    authority_parent_name: '用户管理',
    authority_sort: 4,
    authority_type: '1',
    authority_url: 'user_avatar_review',
    enable: true
  },
  {
    authority_description: '获取待审核头像列表',
    authority_id: 'QOLvuDGrg',
    authority_name: '获取待审核头像列表',
    authority_parent_id: 'F2cVbkCIn',
    authority_parent_name: '用户头像审核',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/user/avatar-review-list',
    enable: false
  },
  {
    authority_description: '审核用户头像',
    authority_id: 'EJB_mpFOS',
    authority_name: '审核用户头像',
    authority_parent_id: 'F2cVbkCIn',
    authority_parent_name: '用户头像审核',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/user/avatar-review-set',
    enable: false
  },
  {
    authority_description: '禁言用户的评论或文章',
    authority_id: 'FH-mt55wt',
    authority_name: '禁言评论或文章',
    authority_parent_id: 'lnRP0Lc5L',
    authority_parent_name: '用户',
    authority_sort: 3,
    authority_type: '2',
    authority_url: '/user/ban',
    enable: false
  },
  {
    authority_description: 'dynamic',
    authority_id: 'xWIFibb79',
    authority_name: '动态管理',
    authority_parent_id: '',
    authority_parent_name: '',
    authority_sort: 4,
    authority_type: '1',
    authority_url: 'dynamic',
    enable: true
  },
  {
    authority_description: '动态话题',
    authority_id: 'iZA1hoZbJ',
    authority_name: '动态话题',
    authority_parent_id: 'xWIFibb79',
    authority_parent_name: '动态管理',
    authority_sort: 0,
    authority_type: '1',
    authority_url: 'dynamicTopic',
    enable: true
  },
  {
    authority_description: '查看所有动态',
    authority_id: 'MopXJpRWJ',
    authority_name: '查看所有动态话题',
    authority_parent_id: 'iZA1hoZbJ',
    authority_parent_name: '动态话题',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/dynamic-topic/all',
    enable: false
  },
  {
    authority_description: '获取动态话题列表',
    authority_id: 'yzTgrYRj1',
    authority_name: '获取动态话题列表',
    authority_parent_id: 'iZA1hoZbJ',
    authority_parent_name: '动态话题',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/dynamic-topic/list',
    enable: false
  },
  {
    authority_description: '创建动态话题',
    authority_id: 'rti2yTBeF',
    authority_name: '创建动态话题',
    authority_parent_id: 'iZA1hoZbJ',
    authority_parent_name: '动态话题',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/dynamic-topic/create',
    enable: false
  },
  {
    authority_description: '更新动态话题',
    authority_id: 'TCYdHQC8-',
    authority_name: '更新动态话题',
    authority_parent_id: 'iZA1hoZbJ',
    authority_parent_name: '动态话题',
    authority_sort: 3,
    authority_type: '2',
    authority_url: '/dynamic-topic/update',
    enable: false
  },
  {
    authority_description: '删除动态话题',
    authority_id: 'UKpCTczAb',
    authority_name: '删除动态话题',
    authority_parent_id: 'iZA1hoZbJ',
    authority_parent_name: '动态话题',
    authority_sort: 4,
    authority_type: '2',
    authority_url: '/dynamic-topic/delete',
    enable: false
  },
  {
    authority_description: '动态汇总',
    authority_id: 'x2dKZeadJ',
    authority_name: '动态汇总',
    authority_parent_id: 'xWIFibb79',
    authority_parent_name: '动态管理',
    authority_sort: 1,
    authority_type: '1',
    authority_url: 'dynamics',
    enable: true
  },
  {
    authority_description: '动态列表',
    authority_id: 'eHn4RPta9',
    authority_name: '动态列表',
    authority_parent_id: 'x2dKZeadJ',
    authority_parent_name: '动态汇总',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/dynamic/list',
    enable: false
  },
  {
    authority_description: '动态更新',
    authority_id: 'ng65zQpLN',
    authority_name: '动态更新',
    authority_parent_id: 'x2dKZeadJ',
    authority_parent_name: '动态汇总',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/dynamic/update',
    enable: false
  },
  {
    authority_description: '动态删除',
    authority_id: 'yqKdT3eG4',
    authority_name: '动态删除',
    authority_parent_id: 'x2dKZeadJ',
    authority_parent_name: '动态汇总',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/dynamic/delete',
    enable: false
  },
  {
    authority_description: '动态评论',
    authority_id: 'QlseovySJ',
    authority_name: '动态评论',
    authority_parent_id: 'xWIFibb79',
    authority_parent_name: '动态管理',
    authority_sort: 2,
    authority_type: '1',
    authority_url: 'dynamicComment',
    enable: true
  },
  {
    authority_description: '动态评论列表',
    authority_id: 'nZmLbdb6r',
    authority_name: '动态评论列表',
    authority_parent_id: 'QlseovySJ',
    authority_parent_name: '动态评论',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/dynamic-comment/list',
    enable: false
  },
  {
    authority_description: '动态评论更新',
    authority_id: 'phmbmxXQY',
    authority_name: '动态评论更新',
    authority_parent_id: 'QlseovySJ',
    authority_parent_name: '动态评论',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/dynamic-comment/update',
    enable: false
  },
  {
    authority_description: '动态评论删除',
    authority_id: 'uArCKa7pn',
    authority_name: '动态评论删除',
    authority_parent_id: 'QlseovySJ',
    authority_parent_name: '动态评论',
    authority_sort: 2,
    authority_type: '2',
    authority_url: '/dynamic-comment/delete',
    enable: false
  },
  {
    authority_description: '个人专栏',
    authority_id: 'JBxkiGzwB',
    authority_name: '个人专栏',
    authority_parent_id: 'AaZjGoX4K',
    authority_parent_name: '文章管理',
    authority_sort: 4,
    authority_type: '1',
    authority_url: 'articleBlog',
    enable: true
  },
  {
    authority_description: '获取个人专栏列表',
    authority_id: 'eBoyfUCzY',
    authority_name: '获取个人专栏列表',
    authority_parent_id: 'JBxkiGzwB',
    authority_parent_name: '个人专栏',
    authority_sort: 0,
    authority_type: '2',
    authority_url: '/article-blog/list',
    enable: false
  },
  {
    authority_description: '更新个人专栏',
    authority_id: 'pfbbT36eD',
    authority_name: '更新个人专栏',
    authority_parent_id: 'JBxkiGzwB',
    authority_parent_name: '个人专栏',
    authority_sort: 1,
    authority_type: '2',
    authority_url: '/article-blog/update',
    enable: false
  }
]
